### ISSUE TITLE
Dependencies on ubuntu based distros

### ISSUE THREAD

**Issue by yenda** [status-im/status-dev-cli#18]
It seems like the install requires 

`sudo apt-get install libavahi-compat-libdnssd-dev`

on Mint (Ubuntu tbd)

**Comment by yenda** [comment]
```
yenda@yenda-laptop:~$ npm i -g status-dev-cli
/home/yenda/.nvm/versions/node/v8.9.3/bin/status-dev-cli -> /home/yenda/.nvm/versions/node/v8.9.3/lib/node_modules/status-dev-cli/cli.js

> mdns@2.3.4 install /home/yenda/.nvm/versions/node/v8.9.3/lib/node_modules/status-dev-cli/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/yenda/.nvm/versions/node/v8.9.3/lib/node_modules/status-dev-cli/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
compilation terminated.
dns_sd_bindings.target.mk:153: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/home/yenda/.nvm/versions/node/v8.9.3/lib/node_modules/status-dev-cli/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/yenda/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.13.0-32-generic
gyp ERR! command "/home/yenda/.nvm/versions/node/v8.9.3/bin/node" "/home/yenda/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/yenda/.nvm/versions/node/v8.9.3/lib/node_modules/status-dev-cli/node_modules/mdns
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yenda/.npm/_logs/2018-01-29T12_51_44_724Z-debug.log

```
