### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Alonski** [status-im/status-dev-cli#7]
Hey,
When running `npm i -g status-dev-cli`
I keep getting an error no matter what I try:
```
C:\WINDOWS\system32>npm i -g status-dev-cli
C:\Users\Alon\AppData\Roaming\npm\status-dev-cli -> C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\cli.js

> mdns@2.3.3 install C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns
> node-gyp rebuild


C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  dns_sd.cpp
  dns_service_browse.cpp
  dns_service_enumerate_domains.cpp
  dns_service_get_addr_info.cpp
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_browse.cpp) [C:
\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_enumerate_domai
ns.cpp) [C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_get_addr_info.c
pp) [C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_sd.cpp) [C:\Users\Alon\
AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_process_result.cpp
  dns_service_ref.cpp
  dns_service_ref_deallocate.cpp
  dns_service_ref_sock_fd.cpp
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref.cpp) [C:\Us
ers\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_process_result.
cpp) [C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref_deallocate.
cpp) [C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_register.cpp
  dns_service_resolve.cpp
  dns_service_update_record.cpp
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref_sock_fd.cpp
) [C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  mdns_utils.cpp
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_register.cpp) [
C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_update_record.c
pp) [C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  network_interface.cpp
  socket_watcher.cpp
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_resolve.cpp) [C
:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_ref.cpp
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\mdns_utils.cpp) [C:\Users\A
lon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_create.cpp
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\network_interface.cpp) [C:\
Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\socket_watcher.cpp) [C:\Use
rs\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_deallocate.cpp
  txt_record_set_value.cpp
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_ref.cpp) [C:\Use
rs\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_get_length.cpp
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_create.cpp) [C:\
Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_buffer_to_object.cpp
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_deallocate.cpp)
[C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_set_value.cpp) [
C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  win_delay_load_hook.cc
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_get_length.cpp)
[C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\alon\appdata\roaming\npm\node_modules\status-dev-cli\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Ca
nnot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_buffer_to_object
.cpp) [C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns\build\dns_sd_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Alon\AppData\Roaming\npm\node_modules\status-dev-cli\node_modules\mdns
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
C:\Users\Alon\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "status-dev-cli"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log
npm ERR! code 1
```

**Comment by Alonski** [comment]
Figured out in the end that I need to install Bonjour SDK to be able to install mdns.
After that I managed to get this working

**Comment by gjeanmart** [comment]
Thanks for your answer. I also installed [**Bonjour Print Service** ](https://support.apple.com/kb/DL999?locale=en_US) and it works now perfectly!
